### ISSUE TITLE
fusion-builder

### ISSUE THREAD

**Issue by random-robbie** [topscoder/nuclei-wordfence-cve#12]
Hey,

Just to say fusion-builder CVE's there are 5 templates that need fixing as they do not conform to the normal wp standard readme.

No version number can be found as far as i know but the readme will look like.

```
=== Avada Builder ===
Requires at least: 4.5
Requires PHP: 5.6

````

and thats it.

I found it's easier to check the main wordpress page and use the following.

```

 extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - 'awb-off-canvas\.js\?ver=((\d+\.?)+)\b'

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - 'awb-off-canvas\.js\?ver=((\d+\.?)+)\b'
          ```
