### ISSUE TITLE
CVE-2020-6009 - Incorrect Path

### ISSUE THREAD

**Issue by random-robbie** [topscoder/nuclei-wordfence-cve#15]
Hey,

It looks like there is no readme.txt with this plugin. Only way seems to check the CSS/Js files being loaded on the main page.

I've changed the template to do the following and confirmed this works

```
http:
  - method: GET
    redirects: true
    max-redirects: 3
    path:
      - "{{BaseURL}}/"

    matchers-condition: and
    matchers:
      - type: status
        status:
          - 200

      - type: word
        words:
          - "sfwd-lms"
        part: body

      - type: dsl
        dsl:
          - compare_versions(version, '<= 3.1.5')

    extractors:
      - type: regex
        name: version
        part: body
        group: 1
        internal: true
        regex:
          - '(?mi)learndash_quiz_front.min.css\?ver=([0-9]+\.[0-9]+\.[0-9]+)'

      - type: regex
        name: version
        part: body
        group: 1
        regex:
          - '(?mi)learndash_quiz_front.min.css\?ver=([0-9]+\.[0-9]+\.[0-9]+)'
        ```
